### ISSUE TITLE
Render problem [Insetter-widgets]

### ISSUE THREAD

**Issue by enriquebautista** [chrisbanes/insetter#97] opened 2021-02-17 17:31 UTC
java.lang.NoClassDefFoundError: Could not initialize class dev.chrisbanes.insetter.widgets.constraintlayout.InsetterConstraintLayout$LayoutParams
	at dev.chrisbanes.insetter.widgets.constraintlayout.InsetterConstraintLayout.generateLayoutParams(InsetterConstraintLayout.kt:99)
	at dev.chrisbanes.insetter.widgets.constraintlayout.InsetterConstraintLayout.generateLayoutParams(InsetterConstraintLayout.kt:61)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1125)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:501)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:328)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:373)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:713)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:844)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I can't see preview

**Comment by chrisbanes** [comment] 2021-02-17 19:09
Duplicate of #79

**Closed by chrisbanes** 2021-02-17 19:09 UTC
